### ISSUE TITLE
检测 workspace 是否安装了 umi 或者 dva

### ISSUE THREAD

**Issue by DiamondYuan** [umijs/vscode-extension-umi-pro#20]
如果没有则禁用插件

**Comment by xiaohuoni** [comment]
其实config/config.j|ts和.umirc.j|ts比较友好，因为umi还有其他的用处

**Comment by DiamondYuan** [comment]
> 其实config/config.j|ts和.umirc.j|ts比较友好，因为umi还有其他的用处

有的项目用了老的 antd pro。还是roaddog版本的。也可以顺带支持一下。

**Comment by xiaohuoni** [comment]
多一个老项目的触发条件觉得如何？

**Comment by xiaohuoni** [comment]
用了umi没有用dva的情况，要不要考虑（-。-）！！
