### ISSUE TITLE
TSX文件中dispatch不会提示

### ISSUE THREAD

**Issue by crashsol** [umijs/vscode-extension-umi-pro#48]
在js文件中可以弹出来信息，TSX文件里面写 dispatch，不会自动提示，目前只支持js吗？

**Comment by DiamondYuan** [comment]
不好意思，忘记加了。

**Comment by DiamondYuan** [comment]
0.4.1 解决了这个问题。

**Comment by DiamondYuan** [comment]
如果没有自动更新，在插件那里搜索一下 umi ，就会自动下载最新版了。

**Comment by oraclexudehua** [comment]
我还有个问题就是说  当'.js'的配置文件关联如果不是"files.associations": {
    "*.js": "javascript",
  },这个插件就不会生效。是否可以增加一个配置项，来解决这个问题
