### ISSUE TITLE
如何让他支持 Typescript router

### ISSUE THREAD

**Issue by gensir** [umijs/vscode-extension-umi-pro#59]
我现在用的 Umi Typescript 版本 
如何让工具支持 Typescript router

**Comment by DiamondYuan** [comment]
> 我现在用的 Umi Typescript 版本
> 如何让工具支持 Typescript router

能给一个 demo 么？


一般来说配置一下 

`umi_pro.router_config_path`就好了

**Comment by gensir** [comment]
环境 | 版本
-----:|:--------
OS| Windows_NT x64 10.0.17763
VS Code|1.34.0
Electron| 3.1.8
Chrome| 66.0.3359.181
V8|6.6.346.32

antd 相关插件

名称 | 版本
-------|---------
Ant Design Pro Helper | v0.3.0
Ant Design Snippets | v1.2.0

以下是我的配置：

VS Code 工作区  `.vscode/setting.json` 设置
```
{
  "umi_pro.router_config_path": "/config/router.config.ts"
}
```
umi router 配置 `config/router.config.ts`
```
export default [
  {
    path: '/user',
    component: '../layouts/UserLayout',
    routes: [
      { path: '/user', redirect: '/user/login' },
      { path: '/user/login', name: '立即登录', component: './user/login' },
    ],
  },
  ...
];
```
_在路由 `config/router.config.ts` 中 路由补全可用_

dva models 配置 `src/models/user.ts`
```
...
const UserModel: UserModelType = {
  namespace: 'user',
  ...
  effects: {
    *fetch(_, { call, put }) {
      yield put({ type: 'save', payload: response });
    },
    *fetchCurrent(_, { call, put }) {
        yield put({ type: 'saveCurrentUser', payload: response });
    },
  },
  reducers: {
    saveCurrentUser(state, action) {
      ...
    },
    changeNotifyCount(state, action) {
      ...
    },
  },
};
export default UserModel;
```
###  在这里  Action 没有自动补全/没有悬浮提示/没有引用查看/没有点击跳转

我该如何设置  让vscode 支持这个插件？

另外 dispatch 中 也支持 Action 自动补全等功能吗？
