### ISSUE TITLE
dva-model-extend或者类似的非直出model的支持

### ISSUE THREAD

**Issue by leftstick** [umijs/vscode-extension-umi-pro#64]
举例：

```javascript
import extend from 'dva-model-extend'

import { getUsers } from './userService'
import commonModel from '../helpers/commonModel'

export default extend(commonModel, {
  namespace: 'users',
  state: {
    currentUser: null
  },

  reducers: {
    *getUsers({ payload }, { call, put, select }) {
      const { success, result } = yield call(getUsers)
      if (success) {
        yield put({
          type: 'updateState',
          payload: {
            currentUser: result
          }
        })
      }
    },
  }
})
```

这里的`ExportDefaultDeclaration`的内容，并不是`ObjectExpression`，而是`CallExpression `，这种怎么处理比较好？感觉很难受

**Comment by DiamondYuan** [comment]
> 举例：
> 
> ```js
> import extend from 'dva-model-extend'
> 
> import { getUsers } from './userService'
> import commonModel from '../helpers/commonModel'
> 
> export default extend(commonModel, {
>   namespace: 'users',
>   state: {
>     currentUser: null
>   },
> 
>   reducers: {
>     *getUsers({ payload }, { call, put, select }) {
>       const { success, result } = yield call(getUsers)
>       if (success) {
>         yield put({
>           type: 'updateState',
>           payload: {
>             currentUser: result
>           }
>         })
>       }
>     },
>   }
> })
> ```
> 
> 这里的`ExportDefaultDeclaration`的内容，并不是`ObjectExpression`，而是`CallExpression `，这种怎么处理比较好？感觉很难受

我们约定所有的 extend 函数都叫 modelExtend 怎么样，

**Comment by leftstick** [comment]
> > 举例：
> > ```js
> > import extend from 'dva-model-extend'
> > 
> > import { getUsers } from './userService'
> > import commonModel from '../helpers/commonModel'
> > 
> > export default extend(commonModel, {
> >   namespace: 'users',
> >   state: {
> >     currentUser: null
> >   },
> > 
> >   reducers: {
> >     *getUsers({ payload }, { call, put, select }) {
> >       const { success, result } = yield call(getUsers)
> >       if (success) {
> >         yield put({
> >           type: 'updateState',
> >           payload: {
> >             currentUser: result
> >           }
> >         })
> >       }
> >     },
> >   }
> > })
> > ```
> > 
> > 
> > 这里的`ExportDefaultDeclaration`的内容，并不是`ObjectExpression`，而是`CallExpression `，这种怎么处理比较好？感觉很难受
> 
> 我们约定所有的 extend 函数都叫 modelExtend 怎么样，

这个不好办吧，名字开发人员肯定会随便起的，而且`dva-model-extend`我感受下来受众也并不广泛，很多团队都是自己手写了一个mixin函数，做自己想做的事情，所以我感觉这个要彻底分析挺难得。。。
