### ISSUE TITLE
关于点击引用跳转到定义的问题

### ISSUE THREAD

**Issue by zqcccc** [umijs/vscode-extension-umi-pro#78]
`yarn create umi` 创建的项目里基本上都用到 `'@/component/xxx'` 这种路径来引入各种资源，很神奇的是，即使在不用这个 umi pro 插件的情况下，如果我创建的是 antdpro 的项目，跳转也是可以的，但是如果创建的是 app 的项目就不行，就算我用了插件，app 的项目也是跳转不了的。。。

我的问题是怎么能像 antdpro 的项目那样实现在 vscode 的点击引用跳转到定义的位置这个功能？

这个引用跳转的功能真的是太重要了，希望我描述清楚了:flushed:

**Comment by DiamondYuan** [comment]
> `yarn create umi` 创建的项目里基本上都用到 `'@/component/xxx'` 这种路径来引入各种资源，很神奇的是，即使在不用这个 umi pro 插件的情况下，如果我创建的是 antdpro 的项目，跳转也是可以的，但是如果创建的是 app 的项目就不行，就算我用了插件，app 的项目也是跳转不了的。。。
> 
> 我的问题是怎么能像 antdpro 的项目那样实现在 vscode 的点击引用跳转到定义的位置这个功能？
> 
> 这个引用跳转的功能真的是太重要了，希望我描述清楚了😳

不好意思，这个没看 issue.
这个功能和插件无关，如果是 ts 的项目，只需要配置 ts config 就可以有提示了。

https://github.com/webclipper/web-clipper/blob/2141313c13fb3b4760a1ab3f1e7fd2c2b37ac164/tsconfig.json#L25


如果使用了 webpack,需要同时配置 webpack 的 alias.


https://github.com/webclipper/web-clipper/blob/2141313c13fb3b4760a1ab3f1e7fd2c2b37ac164/webpack/webpack.common.js#L37

**Comment by zqcccc** [comment]
项目刚好是 js 项目，app 的项目在根目录会自动生成这个 webpack.config.js
![image](https://user-images.githubusercontent.com/19168323/69516826-db2a2880-0f8d-11ea-91d7-cadc730414b9.png)
但是仍然不能跳转，不太理解您所说的使用 webpack，umi 的项目配置不都是在配置文件里写吗？
